---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "src/main/resources/ath-container"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"
        versions: [">=22.04"]
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/ArtifactoryContainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/FtpdContainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"
        versions: [">=22.04"]
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"
        versions: [">=22.04"]
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JabberContainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"
        versions: [">=22.04"]
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JavaGitContainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"
        versions: [">=22.04"]
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"
        versions: [">=22.04"]
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/LdapContainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/MailhogContainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SMBContainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"
        versions: [">=22.04"]
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/Tomcat10Container"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ubuntu"
        versions: [">=22.04"]
  - package-ecosystem: "docker"
    directory: "src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitLabContainer"
    schedule:
      interval: "weekly"
